INICIO
    VARIAVEL TEXTO NOME
    VARIAVEL TEXTO SEXO
    VARIAVEL INTEIRO IDADE  
    
    ESCREVER "DIGITE O NOME : "
    LER NOME
    ESCREVER "DIGITE O SEXO : "
    LER SEXO
    ESCREVER "DIGITE A IDADE : "
    LER IDADE
    
    
    SE IDADE < 25 E SEXO = "F" ENTÃO
        ESCREVER NOME, " ESTÁ ACEITA "
    SENÃO
        ESCREVER NOME, " NÃO ESTÁ ACEITA "
                                    
        
   FIMSE
   FIM             
    
   