INICIO 
        VARIAVEL INTEIRO NUMERO
        VARIAVEL TEXTO NOME 
        
        ESCREVER "ENTRE COM SEU NOME : "
        LER NOME
        ESCREVER "ENTRE COM SEU NÚMERO DE CHAMADA : "
        LER NUMERO
        
        SE NUMERO % 2 = 0 ENTAO
            ESCREVER "SEU NÚMERO É PAR"
            SENAO
            ESCREVER "SEU NÚMERO É ÍMPAR"
            FIMSE
        FIM
            